name: CI Java (Spring Boot) con Gradle

on:
  push:
    branches: [ "main-production" ]
  pull_request:
    branches: [ "main" ]

env:
  JAVA_FILE_NAME: google_checks.xml
  VALIDATE_BASH_EXEC: false
  VALIDATE_CHECKOV: false
  VALIDATE_JSCPD: false
  VALIDATE_SHELL_SHFMT: false
  VALIDATE_GOOGLE_JAVA_FORMAT: false #Ya lo estamos formateando así, no tiene sentido verificarlo
  VALIDATE_DOCKERFILE_HADOLINT: false
  VALIDATE_GROOVY: false

jobs:
  deploy:
    if:  (github.event_name == 'pull_request' && github.event.pull_request.base.ref == 'main-production' && github.event.pull_request.head.ref == 'main')
    name: Deploy to Render
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to Render
        run: |
          curl -X POST https://api.render.com/v1/services/${{ secrets.RENDER_ID }}/deploys \
            -H "Authorization: Bearer ${{ secrets.RENDER_TOKEN }}" \
            -H "Content-Type: application/json" \
