name: CI Java (Spring Boot) con Gradle

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  JAVA_FILE_NAME: google_checks.xml
  VALIDATE_BASH_EXEC: false
  VALIDATE_CHECKOV: false
  VALIDATE_JSCPD: false
  VALIDATE_SHELL_SHFMT: false

jobs:
  build:
    name: Lint y Build
    runs-on: ubuntu-latest

    permissions:
      contents: read
      packages: read
      statuses: write

    steps:
    - uses: actions/checkout@v4
      with:
          # para el Linter
          fetch-depth: 0

    - name: Linter
      uses: super-linter/super-linter@v6.6.0  # x-release-please-version
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          
    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'

    - name: Configurar Gradle
      uses: gradle/actions/setup-gradle@417ae3ccd767c252f5661f1ace9f835f9654f2b5 # v3.1.0
    
    - name: Ejecutar Unit Tests
      run: ./gradlew test --console verbose
    
    - name: Build Gradle
      run: ./gradlew build
